version: '3.5'

services:
    db:
        image: 'mysql:8.0.18'
        command: '--default-authentication-plugin=mysql_native_password'
        volumes:
            - "./database:/var/lib/mysql"
            - "./dump:/docker-entrypoint-initdb.d"
        ports:
            - '3307:3306'
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        networks:
            - 'mvc_tp'

networks:
    mvc_tp:
